# AIC NumPy Assignment 1

In [3]:
import numpy as np

In [5]:
print(np.__version__)

1.16.5


In [6]:
# 1 Create a 1D array of numbers from 0 to 19

arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
# 2 Create a 3×3 numpy array of all False’s

array = np.full((3, 3), False, dtype=bool)
array

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [54]:
#3. sorting an array
a = np.array((6,1,5,3,4,2))
a = np.sort(a)
a

array([1, 2, 3, 4, 5, 6])

In [10]:
#4. converting 2-D into 1-D array
i = np.array([(1,2,3),(4,5,6)])
i = i.flatten()
i

array([1, 2, 3, 4, 5, 6])

In [9]:
#5. converting an array to a list
i = np.array([(1,2,3),(4,5,6)])
i = i.tolist()
i


[[1, 2, 3], [4, 5, 6]]

In [13]:
#6. creating an array with desired range
l1 = np.arange(1,10)
l1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#7. creating an array having all values of zeros
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#8. creating an array having all values as ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#9. convert a list into an array
l = [1,4,5,7]
np.array(l)

array([1, 4, 5, 7])

In [17]:
#10. generates a range of values with desired steps
x = np.arange(1,100,10)
print(x)

[ 1 11 21 31 41 51 61 71 81 91]


In [18]:
#11. to check the shape of an array. output shows that it is a 1-D array of 10 elements.
x.shape

(10,)

In [19]:
#12. tells about data type of values
x.dtype

dtype('int32')

In [20]:
#13. tells about dimensionals of an array
x.ndim

1

In [20]:
#14. creating an array of desired shape but data is non-zero
np.empty((7,7))

array([[3.54241967e-312, 3.54242351e-312, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 9.85330622e+165,
        6.67105512e+135],
       [1.43573466e-023, 1.70168697e+214, 9.89803615e+164,
        3.64238782e-143, 9.08254284e+223, 8.33544611e-072,
        1.31344795e-047],
       [2.20811466e+136, 1.61410559e+132, 6.80600208e+212,
        1.42137836e-076, 1.00385544e+218, 1.61410559e+132,
        1.42137876e-076],
       [1.05901196e+218, 1.40023277e+195, 9.16281387e-072,
        2.13446945e+257, 6.61020367e-062, 8.75854915e+136,
        9.02193423e+217],
       [9.89803615e+164, 2.69036568e+276, 6.99177908e+228,
        1.61410559e+132, 9.89803615e+164, 1.92078268e+136,
        9.02193423e+217],
       [5.03037630e+175, 2.83533191e+137, 2.13663628e+161,
        1.46467681e+224, 1.67751539e+243, 4.26137358e+257,
        3.15363899e+161],
       [6.98203027e+252, 9.09102886e+276, 3.77707152e+233,
        2.31655670e-056, 2.46489526e+184, 7.35161510e+223,
        6.79763547

In [21]:
#15. creating an array with single zero value, no size is given through tupple here
np.zeros(())

array(0.)

In [30]:
#16. creating random arrays consisting of 10 elements
i = np.random.randn(10)
j = np.random.randn(10)

In [35]:
#17. Adding two arrays
i + j

array([ 1.34833754, -2.41792003,  1.55636795,  0.39210988, -1.95293417,
       -2.22715592,  2.45019558,  3.31546684,  0.02608788,  0.13364356])

In [36]:
#18. Subtracting two arrays
i - j

array([-0.5730872 ,  1.71632622, -1.35368733, -1.19071936,  2.47479981,
       -1.72923289,  1.4215427 ,  1.31152624, -1.39293177, -0.23547115])

In [32]:
#19. multiplying an array with an integer
2 * i

array([ 0.77525034, -0.70159381,  0.20268062, -0.79860949,  0.52186563,
       -3.95638881,  3.87173828,  4.62699309, -1.36684388, -0.10182759])

In [33]:
#20. Taking the inverse of an array
1 / i

array([  2.57981183,  -2.85065227,   9.8677419 ,  -2.50435293,
         3.83240411,  -0.50551149,   0.51656384,   0.43224616,
        -1.4632249 , -19.64104307])

In [34]:
#21. gives a boolean array of true and false to show if the elements in the array meet the condition or not
i > 0

array([ True, False,  True, False,  True, False,  True,  True, False,
       False])

In [38]:
#22. this function will give the exact elements which meet the desired condition
i[i>0]

array([0.38762517, 0.10134031, 0.26093282, 1.93586914, 2.31349654])

In [39]:
#23.  creating a 2-D array
i = np.array([[1,2,3],[4,5,6]], dtype = int)
i

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
#24. creating an array of 4 with divided values from 0-25
j = np.linspace(0,25,4)
j

array([ 0.        ,  8.33333333, 16.66666667, 25.        ])

In [41]:
#25. creating an 4 x 4 array with all values one
i = np.full((4,4),1)
i

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
#26. creating a 3x3 diagnol array
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
#27.  reshape
i = np.arange(1,7)
i = i.reshape((2,3))
i

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
#28. size of an array
j = np.array(["a","b","c"])
j = j.size
j

3

In [45]:
#29. converting data type of an array
i = np.array([1,2,3,4,5])
i = i.astype(str)
i

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [49]:
#30. resizing an array
b = np.array([1,2,3,4,5,6])
b = np.resize(b, (3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
#31. transpose of 2x3 to 3x2 array
a = np.array([1,2,3,4,5,6])
a = a.reshape((2,3))
a = a.T
a

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
#32. sorting rows of an array
a = np.array([(2,1,5),(0,4,3)])
a = np.sort(a, axis= 1)
a

array([[1, 2, 5],
       [0, 3, 4]])

In [48]:
#33. sorting columns of an array
a = np.array([(4,3,1),(2,0,5)])
a = np.sort(a, axis= 0)
a

array([[2, 0, 1],
       [4, 3, 5]])

In [49]:
#34. getting maximum value
b = np.array([44,34,72,63])
b = np.max(b)
b

72

In [50]:
#35. getting minimum value
a = np.array([44,34,72,63])
a = np.min(a)
a

34

In [51]:
#36. addition of a specific value in each array element
b = np.array([4,8,6,2,5,15])
a = np.add(b,7)
a

array([11, 15, 13,  9, 12, 22])

In [52]:
#37. subtraction of a specific value from  each array element
b = np.array([7,8,6,4,9,6,2,15,10,25])
a = np.subtract(b,1)
a

array([ 6,  7,  5,  3,  8,  5,  1, 14,  9, 24])

In [53]:
#38. taking square root of each element in an array
a = np.array([1,7,8,4,9,10,16,25])
a = np.sqrt(a)
a

array([1.        , 2.64575131, 2.82842712, 2.        , 3.        ,
       3.16227766, 4.        , 5.        ])

In [54]:
#39. assigning single power to an entire array
a1 = np.array([1,2,4,5,7,9,10])
a = np.power(a1,2)
a

array([  1,   4,  16,  25,  49,  81, 100], dtype=int32)

In [55]:
#40. assigning  different power to each different element in an array
a1 = np.array([2,3,4,5,6,7])
a2 = np.array([2,1,1,3,1,2])
a  = np.power(a1,a2)
a

array([  4,   3,   4, 125,   6,  49], dtype=int32)

In [56]:
#41. absolute value of elements in an array
a = np.array([1.01200000,1.600,1.503000,1.4120])
a = np.abs(a)
a

array([1.012, 1.6  , 1.503, 1.412])

In [57]:
#42. rounding off elements in an array
a = np.array([1.01200000,1.600,1.503000,1.4120])
a = np.round(a)
a

array([1., 2., 2., 1.])

In [58]:
#43. round-up to the nearest int value
a = np.array([1.01200000,1.600,1.503000,1.4120])
a = np.ceil(a)
a

array([2., 2., 2., 2.])

In [59]:
#44. round-down to the nearest int value
a = np.array([1.01200000,1.600,1.503000,1.4120])
a = np.floor(a)
a

array([1., 1., 1., 1.])

In [60]:
#45. mean of values
a = np.array([[4,5,6],[5,10,15]])
a = np.mean(a,axis=0)
a

array([ 4.5,  7.5, 10.5])

In [61]:
#46. median of values
a = np.array([[4,5,6],[5,10,15]])
a = np.median(a,axis=1)
a

array([ 5., 10.])

In [62]:
#47. variance of values
a = np.array([4,5,6,5,10,15])
a = np.var(a)
a

14.916666666666666

In [63]:
#48. standard deviation of values
a = np.array([4,5,6,5,10,15])
a = np.std(a)
a

3.8622100754188224

In [64]:
#49. sum of columns in an array 
a = np.array([[4,5,6],[5,10,15]])
a = a.sum(axis=0)
a

array([ 9, 15, 21])

In [65]:
#50. sum of rows in an array
a = np.array([[4,5,6],[5,10,15]])
a = a.sum(axis=1)
a

array([15, 30])

# End of Assignment
#Muaaz Ahmad Saeed
#PIAIC76639